# Generated by Django 5.0 on 2023-12-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
