# Generated by Django 5.0 on 2023-12-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='states',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
