# Generated by Django 5.0 on 2023-12-27 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
