# Generated by Django 5.0 on 2023-12-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0010_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pro_id',
            new_name='procut_id',
        ),
    ]
