# Generated by Django 5.0 on 2023-12-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0011_rename_pro_id_cart_procut_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
