# Generated by Django 5.0 on 2023-12-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0017_multipleproimage'),
        ('ultrasapp', '0012_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('procut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultras_adminapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultrasapp.users')),
            ],
        ),
    ]
