# Generated by Django 5.0 on 2023-12-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0013_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='procut_id',
            new_name='prodcut_id',
        ),
    ]
