# Generated by Django 5.0 on 2023-12-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0015_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField(max_length=10)),
                ('phone', models.BigIntegerField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('order_notes', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
    ]
