# Generated by Django 5.0 on 2023-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0016_billingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
