# Generated by Django 5.0 on 2024-01-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0017_alter_billingdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
