# Generated by Django 5.0 on 2023-12-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
