# Generated by Django 5.0 on 2023-12-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0008_brands_tags_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
