# Generated by Django 5.0 on 2023-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0009_delete_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.CharField(max_length=100)),
            ],
        ),
    ]
