# Generated by Django 5.0 on 2023-12-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0010_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
