# Generated by Django 5.0 on 2023-12-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0011_webusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebUsers',
        ),
    ]
