# Generated by Django 5.0 on 2023-12-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0012_delete_webusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
