# Generated by Django 5.0 on 2023-12-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0013_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('Product_image', models.FileField(default='', upload_to='media/')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultras_adminapp.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultras_adminapp.category')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultras_adminapp.tags')),
            ],
        ),
    ]
