# Generated by Django 5.0 on 2023-12-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultras_adminapp', '0015_multipleproimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProImage',
        ),
    ]
